### ISSUE TITLE
Issue on connecting to the magento connector when the whole flow has been redeployed.

### ISSUE THREAD

**Issue by alex-fernandez** [mulesoft/magento-connector#35]
********************************************************************************
Message               : Failed to invoke getOrder. Message payload is of type: String
Code                  : MULE_ERROR--2
--------------------------------------------------------------------------------
Exception stack is:
1. null (org.mule.api.ConnectionException)
 org.mule.module.magento.MagentoCloudConnector:98 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/ConnectionException.html)
2. Failed to invoke getOrder. Message payload is of type: String (org.mule.api.MessagingException)
 org.mule.module.magento.processors.GetOrderMessageProcessor:139 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html)
--------------------------------------------------------------------------------
Root Exception stack trace:
org.mule.api.ConnectionException
    at org.mule.module.magento.MagentoCloudConnector.initialiseConnector(MagentoCloudConnector.java:98)
    at org.mule.module.magento.connectivity.MagentoCloudConnectorConnectionFactory.makeObject(MagentoCloudConnectorConnectionFactory.java:48)
    at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1179)
   + 3 more (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)
********************************************************************************

**Comment by alex-fernandez** [comment]
Additonal logs.
ERROR 2015-05-06 13:29:59,105 [ActiveMQ Session Task-3] org.mule.retry.notifiers.ConnectNotifier: Failed to connect/reconnect: Work Descriptor. Root Exception was: null. Type: class org.mule.api.ConnectionException
ERROR 2015-05-06 13:29:59,105 [ActiveMQ Session Task-2] org.mule.retry.notifiers.ConnectNotifier: Failed to connect/reconnect: Work Descriptor. Root Exception was: null. Type: class org.mule.api.ConnectionException
ERROR 2015-05-06 13:29:59,108 [ActiveMQ Session Task-3] org.mule.exception.CatchMessagingExceptionStrategy: 
********************************************************************************
Message               : Failed to invoke addOrderComment. Message payload is of type: String
Code                  : MULE_ERROR--2
--------------------------------------------------------------------------------
Exception stack is:
1. null (org.mule.api.ConnectionException)
  org.mule.module.magento.MagentoCloudConnector:98 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/ConnectionException.html)
2. Failed to invoke addOrderComment. Message payload is of type: String (org.mule.api.MessagingException)
  org.mule.module.magento.processors.AddOrderCommentMessageProcessor:173 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html)
--------------------------------------------------------------------------------
Root Exception stack trace:
org.mule.api.ConnectionException
	at org.mule.module.magento.MagentoCloudConnector.initialiseConnector(MagentoCloudConnector.java:98)
	at org.mule.module.magento.connectivity.MagentoCloudConnectorConnectionFactory.makeObject(MagentoCloudConnectorConnectionFactory.java:48)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1179)
    + 3 more (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)
********************************************************************************

ERROR 2015-05-06 13:29:59,109 [ActiveMQ Session Task-2] org.mule.exception.CatchMessagingExceptionStrategy: 
********************************************************************************
Message               : Failed to invoke getOrder. Message payload is of type: String
Code                  : MULE_ERROR--2
--------------------------------------------------------------------------------
Exception stack is:
1. null (org.mule.api.ConnectionException)
  org.mule.module.magento.MagentoCloudConnector:98 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/ConnectionException.html)
2. Failed to invoke getOrder. Message payload is of type: String (org.mule.api.MessagingException)
  org.mule.module.magento.processors.GetOrderMessageProcessor:139 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html)
--------------------------------------------------------------------------------
Root Exception stack trace:
org.mule.api.ConnectionException
	at org.mule.module.magento.MagentoCloudConnector.initialiseConnector(MagentoCloudConnector.java:98)
	at org.mule.module.magento.connectivity.MagentoCloudConnectorConnectionFactory.makeObject(MagentoCloudConnectorConnectionFactory.java:48)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1179)
    + 3 more (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)
********************************************************************************
